import {
  Users,
  GraduationCap,
  DollarSign,
  CreditCard,
  Building2,
  Clock,
  Calendar,
  CalendarDays,
  BookOpen,
  ShoppingCart,
  Library,
  Bus,
  Home,
  type LucideIcon,
} from "lucide-react";

export interface ModuleConfig {
  id: string;
  name: string;
  shortName: string;
  icon: LucideIcon;
  color: string;
  bgColor: string;
  borderColor: string;
  loginPath: string;
  dashboardPath: string;
  description: string;
}

export const moduleConfigs: Record<string, ModuleConfig> = {
  student: {
    id: "student",
    name: "Student Module",
    shortName: "Students",
    icon: GraduationCap,
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-500",
    borderColor: "border-blue-500",
    loginPath: "/student/login",
    dashboardPath: "/student/dashboard",
    description: "Manage student admissions, profiles, and academics",
  },
  hr: {
    id: "hr",
    name: "HR / Staff Module",
    shortName: "HR",
    icon: Users,
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-500",
    borderColor: "border-purple-500",
    loginPath: "/hr/login",
    dashboardPath: "/hr/dashboard",
    description: "Manage staff, vacancies, and HR operations",
  },
  fee: {
    id: "fee",
    name: "Fee Module",
    shortName: "Fees",
    icon: DollarSign,
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-500",
    borderColor: "border-green-500",
    loginPath: "/fee/login",
    dashboardPath: "/fee/dashboard",
    description: "Manage fee vouchers, payments, and collections",
  },
  payroll: {
    id: "payroll",
    name: "Payroll Module",
    shortName: "Payroll",
    icon: CreditCard,
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-500",
    borderColor: "border-teal-500",
    loginPath: "/payroll/login",
    dashboardPath: "/payroll/dashboard",
    description: "Manage staff salaries, allowances, and deductions",
  },
  finance: {
    id: "finance",
    name: "Finance Module",
    shortName: "Finance",
    icon: Building2,
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-500",
    borderColor: "border-indigo-500",
    loginPath: "/finance/login",
    dashboardPath: "/finance/dashboard",
    description: "Manage accounts, vouchers, and financial reports",
  },
  attendance: {
    id: "attendance",
    name: "Attendance Module",
    shortName: "Attendance",
    icon: Clock,
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-500",
    borderColor: "border-orange-500",
    loginPath: "/attendance/login",
    dashboardPath: "/attendance/dashboard",
    description: "Mark and track student attendance",
  },
  timetable: {
    id: "timetable",
    name: "Time Table Module",
    shortName: "Timetable",
    icon: Calendar,
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-500",
    borderColor: "border-pink-500",
    loginPath: "/timetable/login",
    dashboardPath: "/timetable/dashboard",
    description: "Create and manage class and teacher timetables",
  },
  datesheet: {
    id: "datesheet",
    name: "Date Sheet Module",
    shortName: "Date Sheet",
    icon: CalendarDays,
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-500",
    borderColor: "border-red-500",
    loginPath: "/datesheet/login",
    dashboardPath: "/datesheet/dashboard",
    description: "Create and manage exam date sheets",
  },
  curriculum: {
    id: "curriculum",
    name: "Curriculum & Exam Module",
    shortName: "Curriculum",
    icon: BookOpen,
    color: "text-violet-600 dark:text-violet-400",
    bgColor: "bg-violet-500",
    borderColor: "border-violet-500",
    loginPath: "/curriculum/login",
    dashboardPath: "/curriculum/dashboard",
    description: "Manage syllabus, exams, and results",
  },
  pos: {
    id: "pos",
    name: "POS Module",
    shortName: "POS",
    icon: ShoppingCart,
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-500",
    borderColor: "border-emerald-500",
    loginPath: "/pos/login",
    dashboardPath: "/pos/dashboard",
    description: "Point of sale for uniforms, books, and stationery",
  },
  library: {
    id: "library",
    name: "Library Module",
    shortName: "Library",
    icon: Library,
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-500",
    borderColor: "border-amber-500",
    loginPath: "/library/login",
    dashboardPath: "/library/dashboard",
    description: "Manage books, members, and book issues",
  },
  transport: {
    id: "transport",
    name: "Transport Module",
    shortName: "Transport",
    icon: Bus,
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-500",
    borderColor: "border-cyan-500",
    loginPath: "/transport/login",
    dashboardPath: "/transport/dashboard",
    description: "Manage routes, vehicles, and student allocation",
  },
  hostel: {
    id: "hostel",
    name: "Hostel Module",
    shortName: "Hostel",
    icon: Home,
    color: "text-lime-600 dark:text-lime-400",
    bgColor: "bg-lime-500",
    borderColor: "border-lime-500",
    loginPath: "/hostel/login",
    dashboardPath: "/hostel/dashboard",
    description: "Manage hostel rooms, residents, and fees",
  },
};

export const allModules = Object.values(moduleConfigs);
